words:
  - appscheme
  - batcave
  - camelize
  - codepaths
  - deeplink
  - deeplinking
  - finstrong
  - gradlew
  - mxenabled
  - mxmobilewidgetsdkdemo
  - mxwidgetsdkdemo
  - ngrx
  - pipefail
  - tsbuildinfo
  - webbrowser

ignorePaths:
  - cspell.config.yaml
  - docs/widget_callback_props.md
  - example/.gitignore
  - example/Gemfile
  - example/android/**
  - example/ios/**
  - vitest.config.ts
  - tsconfig.json
  - test/setup.ts
